using PdfGate.net.Models;

using Xunit;

namespace PdfGate.net.AcceptanceTests;

/// <summary>
///     Acceptance tests for generate PDF operations against the live API.
/// </summary>
public sealed class GeneratePdfAcceptanceTests : IClassFixture<PdfGateAcceptanceFixture>
{
    private readonly PdfGateAcceptanceFixture _fixture;

    /// <summary>
    ///     Initializes the test class with a shared acceptance fixture.
    /// </summary>
    public GeneratePdfAcceptanceTests(PdfGateAcceptanceFixture fixture)
    {
        _fixture = fixture;
    }

    /// <summary>
    ///     Calls the generate PDF method and verifies completion status.
    /// </summary>
    [Fact]
    public async Task GeneratePdfAsync_ReturnsCompletedStatus()
    {
        PdfGate client = _fixture.GetClientOrSkip();

        var request = new GeneratePdfRequest
        {
            Html =
                "<html><body><h1>Acceptance Test</h1><p>Generated by SDK acceptance test.</p></body></html>"
        };

        PdfGateDocumentResponse response = await client.GeneratePdfAsync(
            request,
            TestContext.Current.CancellationToken);

        Assert.Equal(DocumentStatus.Completed, response.Status);
    }

    /// <summary>
    ///     Verify that the enums are properly serialized
    /// </summary>
    [Fact]
    public async Task GeneratePdfAsync_AcceptsEnumParams()
    {
        PdfGate client = _fixture.GetClientOrSkip();

        var request = new GeneratePdfRequest
        {
            Html =
                "<html><body><h1>Acceptance Test</h1><p>Generated by SDK acceptance test.</p></body></html>",
            PageSizeType = GeneratePdfPageSizeType.A4,
            Margin = new GeneratePdfPageMargin
            {
                Top = "20px", Bottom = "20px", Left = "12px", Right = "12px"
            }
        };

        PdfGateDocumentResponse response = await client.GeneratePdfAsync(
            request,
            TestContext.Current.CancellationToken);

        Assert.Equal(DocumentStatus.Completed, response.Status);
    }
}

/// <summary>
///     Shared fixture for acceptance tests that require a configured API client.
/// </summary>
public sealed class PdfGateAcceptanceFixture : IDisposable
{
    private const string MissingApiKeyMessage = "Set PDFGATE_API_KEY to run acceptance tests.";
    private readonly PdfGate? _client;

    /// <summary>
    ///     Initializes the client when a test API key is available.
    /// </summary>
    public PdfGateAcceptanceFixture()
    {
        var apiKey = Environment.GetEnvironmentVariable("PDFGATE_API_KEY");
        if (!string.IsNullOrWhiteSpace(apiKey))
            _client = new PdfGate(apiKey);
    }

    /// <summary>
    ///     Returns the configured client or skips the test when no API key is set.
    /// </summary>
    public PdfGate GetClientOrSkip()
    {
        if (_client is null)
            Assert.Skip(MissingApiKeyMessage);

        return _client;
    }

    /// <inheritdoc />
    public void Dispose()
    {
        _client?.Dispose();
    }
}
