using PdfGate.net.Models;

using Xunit;

namespace PdfGate.net.AcceptanceTests;

/// <summary>
///     Acceptance tests for generate PDF operations against the live API.
/// </summary>
public sealed class GeneratePdfAcceptanceTests
{
    /// <summary>
    ///     Calls the generate PDF endpoint with JSON response enabled by the SDK and verifies completion status.
    /// </summary>
    [Fact]
    public async Task GeneratePdfAsync_ReturnsCompletedStatus()
    {
        var apiKey = Environment.GetEnvironmentVariable("PDFGATE_API_KEY");
        if (string.IsNullOrWhiteSpace(apiKey))
            Assert.Skip("Set PDFGATE_API_KEY to run acceptance tests.");

        using var client = new PdfGate(apiKey);

        var request = new GeneratePdfRequest
        {
            Html =
                "<html><body><h1>Acceptance Test</h1><p>Generated by SDK acceptance test.</p></body></html>",
            PageSizeType = GeneratePdfPageSizeType.A4
        };

        PdfGateDocumentResponse response = await client.GeneratePdfAsync(
            request,
            TestContext.Current.CancellationToken);

        Assert.Equal(DocumentStatus.Completed, response.Status);
    }
}
