using PdfGate.net.Models;

using Xunit;

namespace PdfGate.net.AcceptanceTests;

/// <summary>
///     Acceptance tests for generate PDF operations against the live API.
/// </summary>
[Collection(AcceptanceTestCollection.Name)]
public sealed class
    GeneratePdfAcceptanceTests
{
    private readonly PdfGateClientFixture _fixture;

    /// <summary>
    ///     Initializes the test class with a shared acceptance fixture.
    /// </summary>
    public GeneratePdfAcceptanceTests(PdfGateClientFixture fixture)
    {
        _fixture = fixture;
    }

    /// <summary>
    ///     Calls the generate PDF method and verifies completion status.
    /// </summary>
    [Fact]
    public async Task GeneratePdfAsync_ReturnsCompletedStatus()
    {
        PdfGateClient client = _fixture.GetClientOrSkip();

        var request = new GeneratePdfRequest
        {
            Html =
                "<html><body><h1>Acceptance Test</h1><p>Generated by SDK acceptance test.</p></body></html>"
        };

        PdfGateDocumentResponse response = await client.GeneratePdfAsync(
            request,
            TestContext.Current.CancellationToken);

        Assert.Equal(DocumentStatus.Completed, response.Status);
    }

    /// <summary>
    ///     Calls the generate PDF method and verifies completion status.
    /// </summary>
    [Fact]
    public void GeneratePdf_ReturnsCompletedStatus()
    {
        PdfGateClient client = _fixture.GetClientOrSkip();

        var request = new GeneratePdfRequest
        {
            Html =
                "<html><body><h1>Acceptance Test</h1><p>Generated by SDK acceptance test.</p></body></html>"
        };

        PdfGateDocumentResponse response = client.GeneratePdf(
            request,
            TestContext.Current.CancellationToken);

        Assert.Equal(DocumentStatus.Completed, response.Status);
    }

    /// <summary>
    ///     Verify that the enums are properly serialized
    /// </summary>
    [Fact]
    public async Task GeneratePdfAsync_AcceptsEnumParams()
    {
        PdfGateClient client = _fixture.GetClientOrSkip();

        var request = new GeneratePdfRequest
        {
            Html =
                "<html><body><h1>Acceptance Test</h1><p>Generated by SDK acceptance test.</p></body></html>",
            PageSizeType = GeneratePdfPageSizeType.A4,
            Margin = new GeneratePdfPageMargin
            {
                Top = "20px", Bottom = "20px", Left = "12px", Right = "12px"
            }
        };

        PdfGateDocumentResponse response = await client.GeneratePdfAsync(
            request,
            TestContext.Current.CancellationToken);

        Assert.Equal(DocumentStatus.Completed, response.Status);
    }

    /// <summary>
    ///     Verify that the enums are properly serialized
    /// </summary>
    [Fact]
    public void GeneratePdf_AcceptsEnumParams()
    {
        PdfGateClient client = _fixture.GetClientOrSkip();

        var request = new GeneratePdfRequest
        {
            Html =
                "<html><body><h1>Acceptance Test</h1><p>Generated by SDK acceptance test.</p></body></html>",
            PageSizeType = GeneratePdfPageSizeType.A4,
            Margin = new GeneratePdfPageMargin
            {
                Top = "20px", Bottom = "20px", Left = "12px", Right = "12px"
            }
        };

        PdfGateDocumentResponse response = client.GeneratePdf(
            request,
            TestContext.Current.CancellationToken);

        Assert.Equal(DocumentStatus.Completed, response.Status);
    }

    /// <summary>
    ///     Returns a PdfGateException with the HTTP API message when the API returns an error status.
    /// </summary>
    [Fact]
    public async Task
        GeneratePdfAsync_WhenApiReturnsError_ThrowsPdfGateExceptionWithApiMessage()
    {
        PdfGateClient client = _fixture.GetClientOrSkip();

        var request = new GeneratePdfRequest();

        var exception = await Assert.ThrowsAsync<PdfGateException>(() =>
            client.GeneratePdfAsync(request,
                TestContext.Current.CancellationToken));

        Assert.NotNull(exception.StatusCode);
        Assert.False(string.IsNullOrWhiteSpace(exception.ResponseBody));
        Assert.Contains(exception.ResponseBody!, exception.Message,
            StringComparison.Ordinal);
    }

    /// <summary>
    ///     Returns a PdfGateException with the HTTP API message when the API returns an error status.
    /// </summary>
    [Fact]
    public void
        GeneratePdf_WhenApiReturnsError_ThrowsPdfGateExceptionWithApiMessage()
    {
        PdfGateClient client = _fixture.GetClientOrSkip();

        var request = new GeneratePdfRequest();

        var exception = Assert.Throws<PdfGateException>(() =>
            client.GeneratePdf(request,
                TestContext.Current.CancellationToken));

        Assert.NotNull(exception.StatusCode);
        Assert.False(string.IsNullOrWhiteSpace(exception.ResponseBody));
        Assert.Contains(exception.ResponseBody!, exception.Message,
            StringComparison.Ordinal);
    }
}
