using PdfGate.net.Models;

using Xunit;

namespace PdfGate.net.AcceptanceTests;

public sealed class PdfGateDocumentFixture
{
    private PdfGateDocumentResponse? _document;

    /// <summary>
    ///     Returns the configured client or skips the test when no API key is set.
    /// </summary>
    public async Task<PdfGateDocumentResponse> GetDocumentOrSkipAsync(
        PdfGate? client)
    {
        if (_document != null)
            return _document;

        if (client is null)
            Assert.Skip("No client to get an example document");


        var request = new GeneratePdfRequest
        {
            Html =
                "<html><body><h1>Acceptance Test</h1><p>Generated by SDK acceptance test.</p></body></html>"
        };

        PdfGateDocumentResponse response = await client.GeneratePdfAsync(
            request,
            TestContext.Current.CancellationToken);

        _document = response;

        return _document;
    }
}
